apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xc4r
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-xc4r@sha256:f229414d7e4e41f55d7cba01d15b9c98deae385db8c164ae06d6290119b2ae4b
        name: my-nodejs
        resources: {}
status: {}
